### PR TITLE
better error reports

### PR DESCRIPTION
**Pull request by ghost**
borrowed `printCompilerError` from Imba and added `chalk` dependency

it generates errors like this:

```
 - Parse error at [285:0]: Unexpected 'TERMINATOR'
 at /Volumes/Studio/Imba/sandbox/main.imba:11
    ------  ------------------
         8          albums: @albums
         9  
        10      if var album = @albums.filter( do |a| a:id == parseInt(self:params:album) )[0]
        11        on_render_album(null, album)
        12  
    ------  ------------------
```

### CODE REVIEW

**Comment by judofyr** [comment]
It would be nicer if Imba instead provided a way to extract the proper error message. This is very tightly coupled to the current Imba-release and I'm guessing some of the ivars might change in the future.

**Comment by somebee** [comment]
What would you like from the errors? Adding a method for displaying the offending lines with chalk-based highlighting and all seems a little silly, but we could at the very least expose the lineNumber and column. What do you think?

**Comment by ghost** [comment]
why not making the loader report errors the same way `imba compile` does?
smells like discrimination :)

at first i wanted to update Imba's cli to export `printCompilerError` function.
but this also needs to update the function itself so decided to put it into loader itself.
feels like a hack cause it actually was a quick dirty hack that helps me migrate my code.

i agree with @judofyr it's far from optimal solution.
what would you say if i'd add a `compile_with_errors_reporting` or something function to Imba so loaders call it without care about tokens, parsing etc?

**Comment by judofyr** [comment]
Implement the full error message (with the snippet) as `toString` on the error object and Webpack will automatically output it.

**Comment by ghost** [comment]
sounds good, will try

**Pull request closed without merging**
